Controllers/NalazsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using diplomskirad.Data;
using diplomskirad.Models;

namespace konacno.Controllers
{
    public class NalazsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public NalazsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Nalazs
        public async Task<IActionResult> Index()
        {
            var _aplicapplicationDbContext = _context.nalaz.Where(n => n.Email == User.Identity.Name);
            return View(await _aplicapplicationDbContext.ToListAsync());
        }
        public async Task<IActionResult> Index1()
        {
         
            return View(await _context.nalaz.ToListAsync());
        }



        public async Task<IActionResult> Pretraga1(string searchString)
        {

            if (!string.IsNullOrEmpty(searchString))
            {
                var nalaz = _context.nalaz.Where(p => p.Email.Contains(searchString));
                if (nalaz != null && (nalaz as IEnumerable<object>).Any())
                {
                    return View("Index1", await nalaz.ToListAsync());
                }
                else
                {
                    ModelState.AddModelError("Error", "Osoba nije pronadjena");
                    var applicationDbContext = _context.nalaz;
                    return View("Index1", await applicationDbContext.ToListAsync());
                }


            }
            else
            {
                //ModelState.AddModelError("Error", "Check ID");
                var applicationDbContext = _context.nalaz;
                return View("Index1", await applicationDbContext.ToListAsync());


            }
        }

        // GET: Nalazs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nalaz = await _context.nalaz
                .FirstOrDefaultAsync(m => m.NalazID == id);
            if (nalaz == null)
            {
                return NotFound();
            }

            return View(nalaz);
        }

        // GET: Nalazs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Nalazs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NalazID,Opis,Autor,Email,Imeiprezime,Datum,Vrijeme,Brojtelefona")] Nalaz nalaz)
        {
            if (ModelState.IsValid)
            {
                nalaz.Autor = User.Identity.Name;
                _context.Add(nalaz);
                await _context.SaveChangesAsync();
               return RedirectToAction(nameof(Index1));
            }
            return View(nalaz);
        }

        // GET: Nalazs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nalaz = await _context.nalaz.FindAsync(id);
            if (nalaz == null)
            {
                return NotFound();
            }
            return View(nalaz);
        }

        // POST: Nalazs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NalazID,Opis,Autor,Email,Imeiprezime,Datum,Vrijeme,Brojtelefona")] Nalaz nalaz)
        {
            if (id != nalaz.NalazID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(nalaz);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NalazExists(nalaz.NalazID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index1));
            }
            return View(nalaz);
        }

        // GET: Nalazs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nalaz = await _context.nalaz
                .FirstOrDefaultAsync(m => m.NalazID == id);
            if (nalaz == null)
            {
                return NotFound();
            }

            return View(nalaz);
        }

        // POST: Nalazs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var nalaz = await _context.nalaz.FindAsync(id);
            _context.nalaz.Remove(nalaz);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index1));
        }

        private bool NalazExists(int id)
        {
            return _context.nalaz.Any(e => e.NalazID == id);
        }
    }
}

Controllers/UsersController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using diplomskirad.Data;
using diplomskirad.Models;

namespace ZavrsniRadIgorMatic.Controllers
{
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly IWebHostEnvironment _WebHostEnvironment;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;

        private readonly RoleManager<IdentityRole> _roleManager;

        public UsersController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager,
            SignInManager<IdentityUser> signInManager)
        {
            _context = context;
            _WebHostEnvironment = webHostEnvironment;
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> GetUsers()
        {
            var users = await _userManager.Users.ToListAsync();
            var userRolesViewModel = new List<UserRoles>();
            foreach (var user in users)
            {

                var thisViewModel = new UserRoles();
                thisViewModel.KorisnickiID = user.Id;
                thisViewModel.Email = user.Email;
                thisViewModel.BrojTelefona = user.PhoneNumber;
                if (thisViewModel.BrojTelefona == null)
                {
                    thisViewModel.BrojTelefona = "Broj telefona nije unijet";
                }

                thisViewModel.Roles = await GetUserRoles(user);
                if (thisViewModel.Roles[0] == "Pacijent")
                {
                    userRolesViewModel.Add(thisViewModel);
                }
            }
            return View(userRolesViewModel);
        }
        public async Task<IActionResult> GetLaborant()
        {
            var users = await _userManager.Users.ToListAsync();
            var userRolesViewModel = new List<UserRoles>();
            foreach (var user in users)
            {

                var thisViewModel = new UserRoles();
                thisViewModel.KorisnickiID = user.Id;
                thisViewModel.Email = user.Email;
                thisViewModel.BrojTelefona = user.PhoneNumber;
                if (thisViewModel.BrojTelefona == null)
                {
                    thisViewModel.BrojTelefona = "Broj telefona nije unijet";
                }

                thisViewModel.Roles = await GetUserRoles(user);
                if (thisViewModel.Roles[0] == "Laborant")
                {
                    userRolesViewModel.Add(thisViewModel);
                }
            }
            return View(userRolesViewModel);
        }
        private async Task<List<string>> GetUserRoles(IdentityUser user)
        {
            return new List<string>(await _userManager.GetRolesAsync(user));
        }
        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            UserRoles us = new UserRoles();
            us.KorisnickiID = user.Id;
            us.Email = user.Email;
            us.BrojTelefona = user.PhoneNumber;
            if (us.BrojTelefona == null)
            {
                us.BrojTelefona = "Broj telefona nije unijet";
            }
            var roles = await _userManager.GetRolesAsync(user);
            us.Roles = roles.ToList();

            return View("Delete", us);
        }
        public async Task<IActionResult> Delete2(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            UserRoles us = new UserRoles();

            var roles = await _userManager.GetRolesAsync(user);
            us.Roles = roles.ToList();
            IdentityResult result = await _userManager.DeleteAsync(user);
            if (us.Roles[0] == "Pacijent")
            {
                return RedirectToAction("GetUsers");
            }
            else
            {
                return RedirectToAction("GetLaborant");
            }

        }
        public async Task<IActionResult> Manage(string userId)
        {
            ViewBag.userId = userId;
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"Korisnik sa = {userId} nije pronadjen";
                return View("Nije pronadjen");
            }
            ViewBag.UserName = user.UserName;
            var model = new List<RolesViewModel>();
            foreach (var role in _roleManager.Roles)
            {
                var userRolesViewModel = new RolesViewModel
                {
                    UlogeID = role.Id,
                    UlogeIme = role.Name
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.Selektovano = true;
                }
                else
                {
                    userRolesViewModel.Selektovano = false;
                }
                model.Add(userRolesViewModel);
            }
            return View("ChangeRole", model);
        }
        [HttpPost]
        public async Task<IActionResult> Manage(List<RolesViewModel> model, string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return View();
            }
            var roles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, roles);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Nije moguce ukloniti postojece uloge korisnika");
                return View(model);
            }
            result = await _userManager.AddToRolesAsync(user, model.Where(x => x.Selektovano).Select(y => y.UlogeIme));
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Nije moguce ukloniti postojece uloge korisnika");
                return View(model);
            }
            if (model.Where(x => x.Selektovano).Select(y => y.UlogeIme).FirstOrDefault() == "Pacijent")
            {
                return RedirectToAction("GetUsers");
            }
            else
            {
                return RedirectToAction("GetLaborant");
            }

        }



    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Laboratorija</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
    <header>
        <a asp-area="" asp-controller="Laboratorijas" asp-action="Index">

            <div class="d-flex justify-content-around p-0 mb-0 bg-light text-dark ">
                <div>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone" viewBox="0 0 16 16">
                        <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z" />
                    </svg>
                    <small> <strong> <em>LAB SARAJEVO</em> </strong></small> <em>+387 66 852 100</em>
                </div>
                <div>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone" viewBox="0 0 16 16">
                        <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z" />
                    </svg>
                    <small> <strong> <em>LAB LUKAVICA</em> </strong></small> <em>+387 66 852 100</em>
                </div>
                <div>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone" viewBox="0 0 16 16">
                        <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z" />
                    </svg>
                    <small> <strong> <em>LAB DOBRINJA</em> </strong></small> <em>+387 66 852 100</em>
                </div>
                <div>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope" viewBox="0 0 16 16">
                        <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z" />
                    </svg>
                    <small> <strong><em>  EMAIL </em></strong></small> <em>lab@gmail.com</em>
                </div>
            </div>
        </a>
    </header>
    <header>
        @Html.Partial("_navbar.cshtml")
    </header>

    <div class="container body-container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container" style="font-size:20px;font-family:cursive">
           

                &copy; 2022 - M-Lab - <a asp-area="" asp-controller="Home" asp-action="Privacy">Politika privatnosti</a>
           
            <a style="background-color:blue;text-align:center;color:white;" class="btn-floating btn-large btn-fb" href="https://sr-rs.facebook.com/alfalablaboratorija/"><i class="fa fa-facebook" style="width:25px;height:20px"></i></a>

            <a style="background-color:hotpink;text-align:center;color:white;" class="btn-floating btn-large btn-fb" href="https://www.instagram.com/biomedica_laboratorije/"><i class="fa fa-instagram" style="width:25px;height:20px"></i></a>

        </div>
            </footer>
 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)



</body>
</html>

Views/Shared/_navbar.cshtml
<style>
    #button1 {
      font-family:cursive;
      font-size:20px;
      margin-bottom:0px;
    }
    #navbar{

        font-size:20px;
        font-family:cursive;
    }

</style>



<nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="navbar" >
    <div class="container">
        <a class="navbar-brand mt-0 mt-lg-0 " href="#">
            <img class="mx-auto rounded-circle" src="~/Images/slikazakartice.PNG" alt="" width="45" height="35">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

            <ul class="navbar-nav flex-grow-1">

                <li class="nav-item">

                    <a class="nav-link text-dark " asp-area="" asp-controller="Home" asp-action="Index">M-Lab</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark " asp-area="" asp-controller="Home" asp-action="Index">O nama</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Informacijas" asp-action="Index">Informacije</a>
                </li>
                <li class="nav-item dropdown">

                    <button type="button" id="button1" class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        Analize
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="TipAnalizes" asp-action="Index1" asp-route-id=1>Mikrobiologija</a>
                        <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="TipAnalizes" asp-action="Index1" asp-route-id=2>Biohemija</a>
                        <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="TipAnalizes" asp-action="Index1" asp-route-id=3>Genetika</a>

                        
                    </div>

                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Analizes" asp-action="GetList">Cjenovnik</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Laboratorijas" asp-action="Index">Laboratorije</a>
                </li>

                @if (User.IsInRole("Pacijent"))
                {

                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Nalazs" asp-action="Index">Moji nalazi</a>
                    </li>
                }
                @if (User.IsInRole("Laborant") || User.IsInRole("Administrator"))
                {

                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Nalazs" asp-action="Index1">Nalazi</a>
                    </li>
                }
                @* <li class="nav-item dropdown">

            <button type="button" id="button1" class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="font-weight:bold">
                Korisnici
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="TipAnalizes" asp-action="Index" asp-route-id=1>Zaposleni</a>
                <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="TipAnalizes" asp-action="Index" asp-route-id=2>Pacijenti</a>




            </div>

        </li>
                *@

                @if (User.IsInRole("Administrator") || User.IsInRole("Laborant"))
                {
                    <li class="nav-item dropdown">
                        <button type="button" id="button1" class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            Uloge
                        </button>
                        <div class="dropdown-menu">

                            @if (User.IsInRole("Administrator"))
                            {

                                <a class="dropdown-item" asp-controller="Users" asp-action="GetLaborant">Laboranti</a>
                                <a class="dropdown-item" asp-controller="Users" asp-action="GetUsers">Pacijenti</a>

                                // <div class="dropdown-divider"></div>
                                //<a class="dropdown-item" asp-controller="Home" asp-action="Panel">Panel</a>

                            }
                            @if (User.IsInRole("Laborant"))
                            {
                                <a class="dropdown-item" asp-controller="Users" asp-action="GetUsers">Pacijenti</a>


                            }





                        </div>
                    </li>

                }
            </ul>
            <partial name="_LoginPartial" />
           
        </div>
    </div>
   
</nav>