Models/Rezervacija.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace diplomskirad.Models
{
    public class Rezervacija
    {
        [Required]
        [Key]
        public int RezervacijaID { get; set; }
        [Required(ErrorMessage = "Polje Ime i prezime je obavezno")]
        public string Autor { get; set; }
        [Required]
        public string Email { get; set; }
        [Required(ErrorMessage = "Polje Broj telefona je obavezno")]
        [DisplayName("Broj telefona")]
        public string BrojTelefona { get; set; }
        [Required(ErrorMessage = "Polje Datum je obavezno")]
        [DataType(DataType.Date)]
        public DateTime Datum { get; set; }
        [Required(ErrorMessage = "Polje Vrijeme je obavezno")]
        [DataType(DataType.Time)]
        public DateTime Vrijeme { get; set; }
       
       public TipAnalize TipAnalize { get; set; }
        public int TipAnalizeID { get; set; }
        public Laboratorija Laboratorija { get; set; }
        public int LaboratorijaID { get; set; }
    }
}

Controllers/RezervacijasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using diplomskirad.Data;
using diplomskirad.Models;
using Microsoft.AspNetCore.Authorization;

namespace diplomskirad.Controllers
{
    public class RezervacijasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RezervacijasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Rezervacijas
        public async Task<IActionResult> Index()
        {
           
            var applicationDbContext = _context.rezervacija.Include(r => r.Laboratorija).Include(r => r.TipAnalize);
  
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Rezervacijas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rezervacija = await _context.rezervacija
                .Include(r => r.Laboratorija)
                .Include(r => r.TipAnalize)
                .FirstOrDefaultAsync(m => m.RezervacijaID == id);
            if (rezervacija == null)
            {
                return NotFound();
            }

            return View(rezervacija);
        }
        [Authorize]
        // GET: Rezervacijas/Create
        public IActionResult Create()
        {
            ViewData["LaboratorijaID"] = new SelectList(_context.laboratorija, "LaboratorijaID", "Lokacija");
            ViewData["TipAnalizeID"] = new SelectList(_context.tipanalize, "TipAnalizeID", "Naziv");
     
            return View();
        }

        // POST: Rezervacijas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RezervacijaID,Autor,Email,BrojTelefona,Datum,Vrijeme,TipAnalizeID,LaboratorijaID")] Rezervacija rezervacija)
        {

            if (ModelState.IsValid)//objekat koji kreiram rezervaiju u ovom slucaju
            {

                rezervacija.Email = User.Identity.Name;
                    _context.Add(rezervacija);
                ViewBag.poruka = "Uspjesna rezervacija!";
                await _context.SaveChangesAsync();
                //   return RedirectToAction(nameof(Create));

             
                ViewData["LaboratorijaID"] = new SelectList(_context.laboratorija, "LaboratorijaID", "Lokacija");
                ViewData["TipAnalizeID"] = new SelectList(_context.tipanalize, "TipAnalizeID", "Naziv");
                // ViewData["LaboratorijaID"] = new SelectList(_context.laboratorija, "LaboratorijaID", "Lokacija", rezervacija.LaboratorijaID);

                // ViewData["TipAnalizeID"] = new SelectList(_context.tipanalize, "TipAnalizeID", "Naziv", rezervacija.TipAnalizeID);
                ModelState.Clear();
                return View("Create");
            }
          
            return View(rezervacija);
        }

        // GET: Rezervacijas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rezervacija = await _context.rezervacija.FindAsync(id);
            if (rezervacija == null)
            {
                return NotFound();
            }
            ViewData["LaboratorijaID"] = new SelectList(_context.laboratorija, "LaboratorijaID", "Lokacija", rezervacija.LaboratorijaID);
            ViewData["TipAnalizeID"] = new SelectList(_context.tipanalize, "TipAnalizeID", "Naziv", rezervacija.TipAnalizeID);
            return View(rezervacija);
        }

        // POST: Rezervacijas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RezervacijaID,Autor,Email,BrojTelefona,Datum,Vrijeme,TipAnalizeID,LaboratorijaID")] Rezervacija rezervacija)
        {
            if (id != rezervacija.RezervacijaID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rezervacija);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RezervacijaExists(rezervacija.RezervacijaID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LaboratorijaID"] = new SelectList(_context.laboratorija, "LaboratorijaID", "Lokacija", rezervacija.LaboratorijaID);
            ViewData["TipAnalizeID"] = new SelectList(_context.tipanalize, "TipAnalizeID", "Naziv", rezervacija.TipAnalizeID);
            return View(rezervacija);
        }

        // GET: Rezervacijas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rezervacija = await _context.rezervacija
                .Include(r => r.Laboratorija)
                .Include(r => r.TipAnalize)
                .FirstOrDefaultAsync(m => m.RezervacijaID == id);
            if (rezervacija == null)
            {
                return NotFound();
            }

            return View(rezervacija);
        }

        // POST: Rezervacijas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var rezervacija = await _context.rezervacija.FindAsync(id);
            _context.rezervacija.Remove(rezervacija);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RezervacijaExists(int id)
        {
            return _context.rezervacija.Any(e => e.RezervacijaID == id);
        }
    }
}

Views/Rezervacijas/Create.cshtml
@model diplomskirad.Models.Rezervacija

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>


   @* .div-wrapper {
        height: 200px;
        margin-top: 40px;
        border: 2px dashed #ddd;
        border-radius: 8px;
    }

    .div-to-align {
        width: 75%;
        padding: 40px 20px;
        /* .... */
    }*@
</style>
<h1 style="text-align:center;font-size:40px">Zakazi svoj termin</h1>

@if (ViewBag.poruka != null)
{
   
<div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="alert alert-success" role="alert" style="text-align:center;width:50%;font-family:cursive">
            <strong>USPJESNO!</strong> USPJESNO STE REZERVISALI SVOJ TERMIN!
        </div>
    </div>
    </div>
    <script>
        window.setTimeout(function () {
            $(".alert").fadeTo(500, 0).slideUp(1000, function () {
                $(this).remove();
            });
        }, 2000);
    </script>


    }

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-10 col-md-8 col-lg-6" style="background-color:pink">
                <form asp-action="Create" asp-controller="Rezervacijas">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Autor" class="control-label">Ime i prezime:</label>
                        <input asp-for="Autor" class="form-control" />
                        <span asp-validation-for="Autor" class="text-danger"></span>
                    </div>

                    <div class="form-group" style="display: none; visibility: hidden;">
                        <label asp-for="Email" class="control-label">Email</label>
                        <input asp-for="Email" class="form-control" value="Email" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="BrojTelefona" class="control-label"></label>
                        <input asp-for="BrojTelefona" class="form-control" />
                        <span asp-validation-for="BrojTelefona" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Datum" class="control-label"></label>
                        <input asp-for="Datum" class="form-control" />
                        <span asp-validation-for="Datum" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Vrijeme" class="control-label"></label>
                        <input asp-for="Vrijeme" class="form-control" />
                        <span asp-validation-for="Vrijeme" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                
                        <label asp-for="TipAnalizeID" class="control-label">Vrsta analize</label>
                        <select asp-for="TipAnalizeID" class="form-control" asp-items="ViewBag.TipAnalizeID">
                            <option>---Izaberi analizu---</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label asp-for="LaboratorijaID" class="control-label">Laboratorija</label>
                        <select asp-for="LaboratorijaID" class="form-control" asp-items="ViewBag.LaboratorijaID">
                            <option>---Izaberi laboratoriju---</option>
                        </select>
                    </div>
                    <br />
                    <div class="form-group">
                        <input type="submit" value="Potvrdi" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
        @if (User.IsInRole("Laborant") || User.IsInRole("Administrator"))
        {
            <div style="text-align:center;font-size:35px;">
                <a asp-action="Index" style="font-family:cursive;color:black;">Pogledaj sve rezervacije</a>
            </div>
        }
    </div>
    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

Views/Rezervacijas/Delete.cshtml
@model diplomskirad.Models.Rezervacija

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h1>Da li ste sigurni da zelite obrisati Rezervaciju?</h1>
<div>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BrojTelefona)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BrojTelefona)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Datum)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Datum)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Vrijeme)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Vrijeme)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TipAnalize)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipAnalize.Naziv)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Laboratorija)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Laboratorija.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete"  style="font-family:cursive">
        <input type="hidden" asp-for="RezervacijaID" />
        <input type="submit" value="Obrisi" class="btn btn-danger" /> |
        <a asp-action="Index"  style="font-family:cursive">Vrati se</a>
    </form>
</div>

Views/Rezervacijas/Details.cshtml
@model diplomskirad.Models.Rezervacija

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detalji o Rezervaciji</h1>

<div>
  
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BrojTelefona)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BrojTelefona)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Datum)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Datum)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Vrijeme)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Vrijeme)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TipAnalize)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipAnalize.Naziv)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Laboratorija)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Laboratorija.Email)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit"  style="font-family:cursive" asp-route-id="@Model.RezervacijaID">Izmijeni</a> |
    <a asp-action="Index"  style="font-family:cursive">Vrati se</a>
</div>

Views/Rezervacijas/Edit.cshtml
@model diplomskirad.Models.Rezervacija

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Izmijeni Rezervaciju</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RezervacijaID" />
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrojTelefona" class="control-label"></label>
                <input asp-for="BrojTelefona" class="form-control" />
                <span asp-validation-for="BrojTelefona" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Datum" class="control-label"></label>
                <input asp-for="Datum" class="form-control" />
                <span asp-validation-for="Datum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vrijeme" class="control-label"></label>
                <input asp-for="Vrijeme" class="form-control" />
                <span asp-validation-for="Vrijeme" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipAnalizeID" class="control-label"></label>
                <select asp-for="TipAnalizeID" class="form-control" asp-items="ViewBag.TipAnalizeID"></select>
                <span asp-validation-for="TipAnalizeID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LaboratorijaID" class="control-label"></label>
                <select asp-for="LaboratorijaID" class="form-control" asp-items="ViewBag.LaboratorijaID"></select>
                <span asp-validation-for="LaboratorijaID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Sacuvaj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"  style="font-family:cursive">Vrati se</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Rezervacijas/Index.cshtml
@model IEnumerable<diplomskirad.Models.Rezervacija>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div style="font-size:40px;text-align:center">Spisak rezervacija</div>

<table  class="table table-hover table-striped">
    <thead>
        <tr>
            <th>
                Ime i prezime
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BrojTelefona)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Datum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vrijeme)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipAnalize)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Laboratorija)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Autor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BrojTelefona)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Datum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vrijeme)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipAnalize.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Laboratorija.Lokacija)
            </td>
            <td>
                <a asp-action="Edit" style="font-family:cursive" asp-route-id="@item.RezervacijaID">Izmijeni</a> |
                <a asp-action="Details" style="font-family:cursive" asp-route-id="@item.RezervacijaID">Detalji</a> |
                <a asp-action="Delete" style="font-family:cursive" asp-route-id="@item.RezervacijaID">Obrisi</a>
            </td>
        </tr>
}
    </tbody>
</table>