Models/Informacija.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace diplomskirad.Models
{
    public class Informacija
    {
        [Required]
        [Key]
        public int InformacijaID { get; set; }
        [Required]
        public string Naslov { get; set; }
        [Required]
        public string Opis { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayName("Datum dogadjaja")]
        public DateTime DatumDogadjaja { get; set; }
        [Required]
        [DataType(DataType.Time)]
        public DateTime Od { get; set; }
        [Required]
        [DataType(DataType.Time)]
        public DateTime Do { get; set; }
        [Required]
        [Display(Name ="Datum i vrijeme objave")]
        public DateTime DatumIVrijemeObjave { get; set; }
        public string Autor { get; set; }
        [Required]
        public string Slika { get; set; }

        public List<Komentar> Komentar { get; set; } = new List<Komentar>();

    }
}

Models/ViewModels/InformacijaViewModels.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace diplomskirad.Models.ViewModels
{
    public class InformacijaViewModels
    {
        [Required]
        [Key]
        public int InformacijaID { get; set; }
        [Required]
        public string Naslov { get; set; }
        [Required]
        public string Opis { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime DatumDogadjaja { get; set; }
        [Required]
        [DataType(DataType.Time)]
        public DateTime Od { get; set; }
        [Required]
        [DataType(DataType.Time)]
        public DateTime Do { get; set; }
        [Required]
        public DateTime DatumIVrijemeObjave { get; set; }
        public string Autor { get; set; }
        [Required]
        [NotMapped]
        public IFormFile Slika { get; set; }

        public List<Komentar> Komentar { get; set; } = new List<Komentar>();
    }
}

ViewModels/InformacijaViewModels.cs
using diplomskirad.Models;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace diplomskirad.ViewModels
{
    public class InformacijaViewModels
    {
        [Required]
        [Key]
        public int InformacijaID { get; set; }
        [Required]
        public string Naslov { get; set; }
        [Required]
        public string Opis { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime DatumDogadjaja { get; set; }
        [Required]
        [DataType(DataType.Time)]
        public DateTime Od { get; set; }
        [Required]
        [DataType(DataType.Time)]
        public DateTime Do { get; set; }
        [Required]
        public DateTime DatumIVrijemeObjave { get; set; }
        public string Autor { get; set; }
        [Required]
        [NotMapped]
        public IFormFile Slika { get; set; }

        public List<Komentar> Komentar { get; set; } = new List<Komentar>();
    }
}

Controllers/InformacijasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using diplomskirad.Data;
using diplomskirad.Models;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using diplomskirad.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace diplomskirad.Controllers
{
    public class InformacijasController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _WebHostEnvironment;

        public InformacijasController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _WebHostEnvironment = webHostEnvironment;
        }

        // GET: Informacijas
        public async Task<IActionResult> Index()
        {
            return View(await _context.informacija.ToListAsync());
        }

        // GET: Informacijas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var informacija = await _context.informacija
                .FirstOrDefaultAsync(m => m.InformacijaID == id);
            if (informacija == null)
            {
                return NotFound();
            }

            return View(informacija);
        }

        // GET: Informacijas/Create
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Create1()
        {
            return View();

        }


        // POST: Informacijas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InformacijaID,Naslov,Opis,DatumDogadjaja,Od,Do,DatumIVrijemeObjave,Autor,Slika")] Informacija informacija)
        {
            if (ModelState.IsValid)
            {
                _context.Add(informacija);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(informacija);
        }
        [Authorize]
        [HttpPost]
   /**/    
        public IActionResult Create1(InformacijaViewModels model)
        {
            string stringFileName = UploadFile(model);
            var Informacija = new Informacija
            {

                Naslov = model.Naslov,
                Opis = model.Opis,
                DatumDogadjaja = model.DatumDogadjaja,
                Od=model.Od,
                Do=model.Do,
                DatumIVrijemeObjave=DateTime.Now,
                Autor = model.Autor,
                Slika = stringFileName
            };
            _context.informacija.Add(Informacija);//dodavanje u bazu
            _context.SaveChanges();
            return RedirectToAction("Index");

        }
        private string UploadFile(InformacijaViewModels model)
        {
            string fileName = null;
            if (model.Slika != null)
            {
                string UploadDir = Path.Combine(_WebHostEnvironment.WebRootPath, "Images");//smjesti sliku koju si dodao u folder images
                fileName = Guid.NewGuid().ToString() + "-" + model.Slika.FileName; //kovertovanje u string
                string filePath = Path.Combine(UploadDir, fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.Slika.CopyTo(fileStream);
                }
            }
            return fileName;

        }

        // GET: Informacijas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var informacija = await _context.informacija.FindAsync(id);
            if (informacija == null)
            {
                return NotFound();
            }
            return View(informacija);
        }

        // POST: Informacijas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InformacijaID,Naslov,Opis,DatumDogadjaja,Od,Do,DatumIVrijemeObjave,Autor,Slika")] Informacija informacija)
        {
            if (id != informacija.InformacijaID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(informacija);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InformacijaExists(informacija.InformacijaID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(informacija);
        }

        // GET: Informacijas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var informacija = await _context.informacija
                .FirstOrDefaultAsync(m => m.InformacijaID == id);
            if (informacija == null)
            {
                return NotFound();
            }

            return View(informacija);
        }

        // POST: Informacijas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var informacija = await _context.informacija.FindAsync(id);
            _context.informacija.Remove(informacija);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InformacijaExists(int id)
        {
            return _context.informacija.Any(e => e.InformacijaID == id);
        }
    }
}

Views/Informacijas/Create.cshtml
@model diplomskirad.Models.Informacija

@{
    ViewData["Title"] = "Create";
}

<h1 style="font-family:cursive"> Kreiraj Informaciju</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Naslov" class="control-label"></label>
                <input asp-for="Naslov" class="form-control" />
                <span asp-validation-for="Naslov" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumDogadjaja" class="control-label"></label>
                <input asp-for="DatumDogadjaja" class="form-control" />
                <span asp-validation-for="DatumDogadjaja" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Od" class="control-label"></label>
                <input asp-for="Od" class="form-control" />
                <span asp-validation-for="Od" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Do" class="control-label"></label>
                <input asp-for="Do" class="form-control" />
                <span asp-validation-for="Do" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumIVrijemeObjave" class="control-label"></label>
                <input asp-for="DatumIVrijemeObjave" class="form-control" />
                <span asp-validation-for="DatumIVrijemeObjave" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Slika" class="control-label"></label>
                <input asp-for="Slika" class="form-control" />
                <span asp-validation-for="Slika" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Kreiraj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" style="font-family:cursive">Vrati se</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Informacijas/Create1.cshtml
@model diplomskirad.Models.ViewModels.InformacijaViewModels
    <h1 style="font-family:cursive"> Kreiraj Informaciju</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create1" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Naslov" class="control-label"></label>
                <input asp-for="Naslov" class="form-control" />
                <span asp-validation-for="Naslov" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumDogadjaja" class="control-label">Datum dogadjaja</label>
                <input asp-for="DatumDogadjaja" class="form-control" />
                <span asp-validation-for="DatumDogadjaja" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Od" class="control-label"></label>
                <input asp-for="Od" class="form-control" />
                <span asp-validation-for="Od" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Do" class="control-label"></label>
                <input asp-for="Do" class="form-control" />
                <span asp-validation-for="Do" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none; visibility:hidden;">
                <label asp-for="DatumIVrijemeObjave" class="control-label"></label>
                <input asp-for="DatumIVrijemeObjave" class="form-control" />
                <span asp-validation-for="DatumIVrijemeObjave" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Slika" class="control-label"></label>
                <input asp-for="Slika" class="form-control" />
                <span asp-validation-for="Slika" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Kreiraj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" style="font-family:cursive">Vrati se</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Informacijas/Delete.cshtml
@model diplomskirad.Models.Informacija

@{
    ViewData["Title"] = "Delete";
}



<h1 style="font-family:cursive"> Da li ste sigurni da zelite obrisati Informaciju?</h1>
<div>
   
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naslov)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naslov)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Opis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Opis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatumDogadjaja)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatumDogadjaja)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Od)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Od)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Do)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Do)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatumIVrijemeObjave)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatumIVrijemeObjave)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Slika)
        </dt>
        <dd class = "col-sm-10">
           <img  src="~/Images/@Model.Slika" style="width:220px;height:220px;"/> @*ovim postavljam izgled slike*@
        </dd>
    </dl>
    
    <form asp-action="Delete"  style="font-family:cursive">
        <input type="hidden" asp-for="InformacijaID" />
        <input type="submit" value="Obrisi" class="btn btn-danger" /> |
        <a asp-action="Index"  style="font-family:cursive">Vrati se </a>
    </form>
</div>

Views/Informacijas/Details.cshtml
@model diplomskirad.Models.Informacija

@{
    ViewData["Title"] = "Details";
}

<h1 style="font-family:cursive">Detalji o Informaciji</h1>

<div>
   
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naslov)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naslov)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Opis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Opis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatumDogadjaja)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatumDogadjaja)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Od)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Od)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Do)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Do)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatumIVrijemeObjave)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatumIVrijemeObjave)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Slika)
        </dt>
        <dd class = "col-sm-10">
           <img src="~/Images/@Model.Slika" />
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.InformacijaID"  style="font-family:cursive">Izmijeni</a> |
    <a asp-action="Index"  style="font-family:cursive">Vrati se</a>
</div>

Views/Informacijas/Edit.cshtml
@model diplomskirad.Models.Informacija

@{
    ViewData["Title"] = "Edit";
}

<h1>Izmijeni Informaciju</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="InformacijaID" />
            <div class="form-group">
                <label asp-for="Naslov" class="control-label"></label>
                <input asp-for="Naslov" class="form-control" />
                <span asp-validation-for="Naslov" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumDogadjaja" class="control-label"></label>
                <input asp-for="DatumDogadjaja" class="form-control" />
                <span asp-validation-for="DatumDogadjaja" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Od" class="control-label"></label>
                <input asp-for="Od" class="form-control" />
                <span asp-validation-for="Od" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Do" class="control-label"></label>
                <input asp-for="Do" class="form-control" />
                <span asp-validation-for="Do" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumIVrijemeObjave" class="control-label"></label>
                <input asp-for="DatumIVrijemeObjave" class="form-control" />
                <span asp-validation-for="DatumIVrijemeObjave" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Slika" class="control-label"></label>
                <input asp-for="Slika" class="form-control" />
                <span asp-validation-for="Slika" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Sacuvaj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"  style="font-family:cursive">Vrati se</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Informacijas/Index.cshtml
@model IEnumerable<diplomskirad.Models.Informacija>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <style>

        .body-container {
            /*remove the container default padding attribute*/
            padding-left: 0px !important;
            padding-right: 0px !important;
            /*increase width as per your need*/
            max-width: 100%;
            padding-top: 0px!important;
            height:600px;
        }
        .prev, .next {
            cursor: pointer;
           position:absolute;
            top: 50%;
            width: auto;
           
            padding: 10px;
            color: white;
            font-weight: bold;
            font-size: 18px;
            transition: 0.6s ease;
            border-radius: 0 3px 3px 0;
            user-select: none;
            
        }
        /*
        .dugmad {
            position: fixed;
            top: 650px;
            bottom: 0;
            left: 0;
            z-index: 1000;
            padding: 20px 0;
            overflow-x: hidden;
            overflow-y: auto; 

           
        }*/
      
        .next {
        right:0;
       
        }
        .prev {
       left:0;
            }
            .prev:hover, .next:hover {
                background-color: rgba(0,0,0,0.8);
            }
        #div1 {
        background:rgba(0,0,0,0.3);
        }
    </style>

    <div style="width:100%">
        @foreach (var item in Model)
        {



            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">

                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    <div class="carousel-item active">

                        <img src="~/Images/@item.Slika" class="mySlides" id="slika" style="width:100%; height:600px">



                        <div class="carousel-caption" id="div1">
                            <h3 style="font-family:cursive">@item.Naslov</h3>
                            <p style="font-family:cursive">@item.Opis</p>
                            <p class="text-start-b" style="font-family:cursive"><strong>Popust traje od:</strong>@item.Od  <strong> do: </strong> @item.Do</p>
                            <p class="text-end" style="font-family:cursive">Datum objave: @item.DatumDogadjaja</p>
                           @if (User.IsInRole("Administrator") || User.IsInRole("Laborant"))
                           {
                            <a type="button"  style="font-family:cursive" class="btn btn-primary" asp-area="" asp-controller="Informacijas" asp-action="Create1" asp-route-id=@item.InformacijaID>Kreiraj</a>
                           <a type="button"  style="font-family: cursive" class="btn btn-primary" asp-area="" asp-controller="Informacijas" asp-action="Edit" asp-route-id=@item.InformacijaID>Izmijeni</a>
                            <a type="button"  style="font-family: cursive" class="btn btn-primary" asp-area="" asp-controller="Informacijas" asp-action="Delete" asp-route-id=@item.InformacijaID>Obrisi</a>
                           }
                        </div>

                    </div>


                </div>

            </div>
           

        }
        <a class="prev" onclick="plusDivs(-1)">&#10094;</a>

        <a class="next" onclick="plusDivs(1)">&#10095;</a>



    </div>

<script>
    var slideIndex = 1;
    showDivs(slideIndex);

    function plusDivs(n) {
        showDivs(slideIndex += n);
    }

    function showDivs(n) {
        var i;
        var x = document.getElementsByClassName("mySlides");
        if (n > x.length) { slideIndex = 1 }
        if (n < 1) { slideIndex = x.length };
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        x[slideIndex - 1].style.display = "block";
    }
</script>