Models/Nalaz.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace diplomskirad.Models
{
    public class Nalaz
    {
        [Required]
        [Key]
        public int NalazID { get; set; }
        [Required]
        public string Opis { get; set; }
        [Required]
        public string Autor { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        [DisplayName("Ime i prezime")]
        public string Imeiprezime { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime Datum { get; set; }
        [Required]
        [DataType(DataType.Time)]
        public DateTime Vrijeme { get; set; }
        [Required]
        [DisplayName("Broj telefona")]
        public string Brojtelefona { get; set; }
        

        public List<Parametar> Parametar { get; set; } = new List<Parametar>();

    }
}

Controllers/NalazsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using diplomskirad.Data;
using diplomskirad.Models;

namespace konacno.Controllers
{
    public class NalazsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public NalazsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Nalazs
        public async Task<IActionResult> Index()
        {
            var _aplicapplicationDbContext = _context.nalaz.Where(n => n.Email == User.Identity.Name);
            return View(await _aplicapplicationDbContext.ToListAsync());
        }
        public async Task<IActionResult> Index1()
        {
         
            return View(await _context.nalaz.ToListAsync());
        }



        public async Task<IActionResult> Pretraga1(string searchString)
        {

            if (!string.IsNullOrEmpty(searchString))
            {
                var nalaz = _context.nalaz.Where(p => p.Email.Contains(searchString));
                if (nalaz != null && (nalaz as IEnumerable<object>).Any())
                {
                    return View("Index1", await nalaz.ToListAsync());
                }
                else
                {
                    ModelState.AddModelError("Error", "Osoba nije pronadjena");
                    var applicationDbContext = _context.nalaz;
                    return View("Index1", await applicationDbContext.ToListAsync());
                }


            }
            else
            {
                //ModelState.AddModelError("Error", "Check ID");
                var applicationDbContext = _context.nalaz;
                return View("Index1", await applicationDbContext.ToListAsync());


            }
        }

        // GET: Nalazs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nalaz = await _context.nalaz
                .FirstOrDefaultAsync(m => m.NalazID == id);
            if (nalaz == null)
            {
                return NotFound();
            }

            return View(nalaz);
        }

        // GET: Nalazs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Nalazs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NalazID,Opis,Autor,Email,Imeiprezime,Datum,Vrijeme,Brojtelefona")] Nalaz nalaz)
        {
            if (ModelState.IsValid)
            {
                nalaz.Autor = User.Identity.Name;
                _context.Add(nalaz);
                await _context.SaveChangesAsync();
               return RedirectToAction(nameof(Index1));
            }
            return View(nalaz);
        }

        // GET: Nalazs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nalaz = await _context.nalaz.FindAsync(id);
            if (nalaz == null)
            {
                return NotFound();
            }
            return View(nalaz);
        }

        // POST: Nalazs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NalazID,Opis,Autor,Email,Imeiprezime,Datum,Vrijeme,Brojtelefona")] Nalaz nalaz)
        {
            if (id != nalaz.NalazID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(nalaz);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NalazExists(nalaz.NalazID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index1));
            }
            return View(nalaz);
        }

        // GET: Nalazs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nalaz = await _context.nalaz
                .FirstOrDefaultAsync(m => m.NalazID == id);
            if (nalaz == null)
            {
                return NotFound();
            }

            return View(nalaz);
        }

        // POST: Nalazs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var nalaz = await _context.nalaz.FindAsync(id);
            _context.nalaz.Remove(nalaz);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index1));
        }

        private bool NalazExists(int id)
        {
            return _context.nalaz.Any(e => e.NalazID == id);
        }
    }
}

Controllers/SifarniksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using diplomskirad.Data;
using diplomskirad.Models;

namespace konacno.Controllers
{
    public class SifarniksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SifarniksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Sifarniks
        public async Task<IActionResult> Index()
        {
            return View(await _context.sifarnik.ToListAsync());
        }

        // GET: Sifarniks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sifarnik = await _context.sifarnik
                .FirstOrDefaultAsync(m => m.SifarnikID == id);
            if (sifarnik == null)
            {
                return NotFound();
            }

            return View(sifarnik);
        }

        // GET: Sifarniks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Sifarniks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SifarnikID,Naziv,Min,Max,Jedinica")] Sifarnik sifarnik)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sifarnik);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sifarnik);
        }

        // GET: Sifarniks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sifarnik = await _context.sifarnik.FindAsync(id);
            if (sifarnik == null)
            {
                return NotFound();
            }
            return View(sifarnik);
        }

        // POST: Sifarniks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SifarnikID,Naziv,Min,Max,Jedinica")] Sifarnik sifarnik)
        {
            if (id != sifarnik.SifarnikID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sifarnik);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SifarnikExists(sifarnik.SifarnikID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sifarnik);
        }

        // GET: Sifarniks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sifarnik = await _context.sifarnik
                .FirstOrDefaultAsync(m => m.SifarnikID == id);
            if (sifarnik == null)
            {
                return NotFound();
            }

            return View(sifarnik);
        }

        // POST: Sifarniks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sifarnik = await _context.sifarnik.FindAsync(id);
            _context.sifarnik.Remove(sifarnik);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SifarnikExists(int id)
        {
            return _context.sifarnik.Any(e => e.SifarnikID == id);
        }
    }
}

Views/Nalazs/Create.cshtml
@model diplomskirad.Models.Nalaz

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Kreiraj Nalaz</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <div class="form-group"   style="display: none; visibility: hidden;">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" value="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imeiprezime" class="control-label"></label>
                <input asp-for="Imeiprezime" class="form-control" />
                <span asp-validation-for="Imeiprezime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Datum" class="control-label"></label>
                <input asp-for="Datum" class="form-control" />
                <span asp-validation-for="Datum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vrijeme" class="control-label"></label>
                <input asp-for="Vrijeme" class="form-control" />
                <span asp-validation-for="Vrijeme" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brojtelefona" class="control-label"></label>
                <input asp-for="Brojtelefona" class="form-control" />
                <span asp-validation-for="Brojtelefona" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Kreiraj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"  style="font-family:cursive">Vrati se</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Nalazs/Delete.cshtml
@model diplomskirad.Models.Nalaz

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h1>Da li ste sigurni da zelite obrisati Nalaz?</h1>
<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Opis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Opis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imeiprezime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imeiprezime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Datum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Datum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vrijeme)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vrijeme)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brojtelefona)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brojtelefona)
        </dd>
    </dl>
    
    <form asp-action="Delete"  style="font-family:cursive">
        <input type="hidden" asp-for="NalazID" />
        <input type="submit" value="Obrisi" class="btn btn-danger" /> |
        <a asp-action="Index"  style="font-family:cursive">Vrati se</a>
    </form>
</div>

Views/Nalazs/Details.cshtml
@model diplomskirad.Models.Nalaz

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detalji o Nalazu</h1>

<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Opis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Opis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imeiprezime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imeiprezime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Datum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Datum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vrijeme)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vrijeme)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brojtelefona)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brojtelefona)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.NalazID"  style="font-family:cursive">Izmijeni</a> |
    <a asp-action="Index"  style="font-family:cursive">Vrati se  </a>
</div>

Views/Nalazs/Edit.cshtml
@model diplomskirad.Models.Nalaz

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Izmijeni Nalaz</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="NalazID" />
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imeiprezime" class="control-label"></label>
                <input asp-for="Imeiprezime" class="form-control" />
                <span asp-validation-for="Imeiprezime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Datum" class="control-label"></label>
                <input asp-for="Datum" class="form-control" />
                <span asp-validation-for="Datum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vrijeme" class="control-label"></label>
                <input asp-for="Vrijeme" class="form-control" />
                <span asp-validation-for="Vrijeme" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brojtelefona" class="control-label"></label>
                <input asp-for="Brojtelefona" class="form-control" />
                <span asp-validation-for="Brojtelefona" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Sacuvaj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"  style="font-family:cursive">Vrati se  </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Nalazs/Index.cshtml
@model IEnumerable<diplomskirad.Models.Nalaz>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (User.Identity.Name == "Administrator" && User.Identity.Name == ("Laborant"))
{
    <p>
        <a asp-action="Create" style="font-family:cursive">Kreiraj Nalaz</a>
    </p>

}

<p style="font-size: 25px; font-family: cursive">Moji nalazi:</p>
    <table class="table">
        <thead>
            <tr>
                <td>
                    <strong>
                        @Html.DisplayNameFor(model => model.Opis)
                    </strong>
                </td>

                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Imeiprezime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Datum)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vrijeme)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Brojtelefona)
                </th>
                <td>
                    <strong>
                        Laborant
                    </strong>
                </td>
                <th></th>
            </tr>
        </thead>


        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Opis)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Imeiprezime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Datum)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Vrijeme)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Brojtelefona)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Autor)
                    </td>

                    <td>
                        <a asp-area="" asp-controller="Parametars" asp-action="Index2" asp-route-id="@item.NalazID"> Pogledaj nalaz</a>
                        @if (User.Identity.Name == "Administrator" && User.Identity.Name == ("Laborant"))
                        {
                            <a asp-action="Edit" style="font-family:cursive" asp-route-id="@item.NalazID">Izmijeni</a>
                            <a asp-action="Details" style="font-family:cursive" asp-route-id="@item.NalazID">Detalji</a>
                            <a asp-action="Delete" style="font-family:cursive" asp-route-id="@item.NalazID">Obrisi</a>
                        }
                    </td>

                </tr>
            }
        </tbody>

    </table>

Views/Nalazs/Index1.cshtml
@model IEnumerable<diplomskirad.Models.Nalaz>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (!ViewData.ModelState.IsValid && ViewData.ModelState["Error"].Errors.Count > 0)
{
    <div class="alert alert-danger" role="alert" style="margin-top:4rem;">
        Nije pronadjena nijedna osoba sa unijetim emailom!
    </div>
    <script>
        window.setTimeout(function () {
            $(".alert").fadeTo(500, 0).slideUp(1000, function () {
                $(this).remove();
            });
        }, 2000);
    </script>

}

<form asp-controller="Nalazs" asp-action="Pretraga1">
    <p style="font-family: cursive">
        Email:<input type="text" class="form-control" name="SearchString" placeholder="Unesi email osobe" />
        <input type="submit" class="btn btn-primary" style="font-family:cursive" value="Pretrazi" />
    </p>
</form>
<p style="font-size: 25px; font-family: cursive">
    Spisak svih nalaza
</p>
<table class="table table-hover table-striped">
    <thead>
        <tr>
            <td>
                <strong>
                    @Html.DisplayNameFor(model => model.Opis)
                </strong>
            </td>

            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imeiprezime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Datum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vrijeme)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Brojtelefona)
            </th>
            <td>
                <strong>
                    Laborant
                </strong>
            </td>
            <th></th>
        </tr>
    </thead>


    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Opis)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Imeiprezime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Datum)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Vrijeme)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Brojtelefona)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Autor)
                </td>

                <td>
                    <a asp-area="" asp-controller="Parametars" asp-action="Index1" asp-route-id="@item.NalazID"> Pogledaj nalaz</a>

                    <a asp-action="Edit" style="font-family:cursive" asp-route-id="@item.NalazID">Izmijeni</a>
                    <a asp-action="Details" style="font-family:cursive" asp-route-id="@item.NalazID">Detalji</a>
                    <a asp-action="Delete" style="font-family:cursive" asp-route-id="@item.NalazID">Obrisi</a>

                </td>

            </tr>
        }
    </tbody>

</table>
@if (User.IsInRole("Laborant") || User.IsInRole("Administrator"))
{
    <p>
        <a asp-action="Create" style="font-family:cursive">Kreiraj Nalaz</a>

        <a asp-area="" asp-controller="Sifarniks" asp-action="Create" style="font-family:cursive">Kreiraj Parametar</a>

        <a asp-area="" asp-controller="Parametars" asp-action="Create" style="font-family:cursive">Dodijeli parametre nalazu</a>
    </p>
}